// PERSON
INSERT INTO PERSONS(ID, FIRST_NAME, LAST_NAME, MAIL, PASSWORD, ROLE) VALUES (1, 'John-son', 'Hippolyte', 'contact@jhippolyte.com', 'jhippolyte', 'USER');
INSERT INTO PERSONS(ID, FIRST_NAME, LAST_NAME, MAIL, PASSWORD, ROLE) VALUES (2, 'Stephen', 'Curry', 'babyface@gmail.com', 'scurry', 'USER');
INSERT INTO PERSONS(ID, FIRST_NAME, LAST_NAME, MAIL, PASSWORD, ROLE) VALUES (3, 'James', 'Harden', 'james.harden@gmail.com', 'jharden', 'USER');
INSERT INTO PERSONS(ID, FIRST_NAME, LAST_NAME, MAIL, PASSWORD, ROLE) VALUES (4, 'Admin', '', 'admin@jhippolyte.com', 'admin', 'ADMIN');

// BANK_ACCOUNTS
INSERT INTO BANK_ACCOUNTS(ID, ACCOUNT_NUMBER, BALANCE, OVERDRAFT, TYPE, OWNER_ID) VALUES (1, '00000000', 500, 0, 'SAVING', 1);
INSERT INTO BANK_ACCOUNTS(ID, ACCOUNT_NUMBER, BALANCE, OVERDRAFT, TYPE, OWNER_ID) VALUES (2, '11111111', 5000000, 300000, 'CURRENT', 2);
INSERT INTO BANK_ACCOUNTS(ID, ACCOUNT_NUMBER, BALANCE, OVERDRAFT, TYPE, OWNER_ID) VALUES (3, '22222222', 300000, 30000, 'CURRENT', 3);
