// PERSON
INSERT INTO PERSONS(ID, FIRST_NAME, LAST_NAME, MAIL) VALUES (1, 'John-son', 'Hippolyte', 'contact@jhippolyte.com');
INSERT INTO PERSONS(ID, FIRST_NAME, LAST_NAME, MAIL) VALUES (2, 'Stephen', 'Curry', 'babyface@gmail.com');
INSERT INTO PERSONS(ID, FIRST_NAME, LAST_NAME, MAIL) VALUES (3, 'James', 'Harden', 'james.harden@gmail.com');

// BANK_ACCOUNTS
INSERT INTO BANK_ACCOUNTS(ID, ACCOUNT_NUMBER, BALANCE, OVERDRAFT, PASSWORD, TYPE, OWNER_ID) VALUES (1, '00000000', 500, 0, 'jhippolyte', 'saving', 1);
INSERT INTO BANK_ACCOUNTS(ID, ACCOUNT_NUMBER, BALANCE, OVERDRAFT, PASSWORD, TYPE, OWNER_ID) VALUES (2, '11111111', 5000000, 300000, 'scurry', 'current', 2);
INSERT INTO BANK_ACCOUNTS(ID, ACCOUNT_NUMBER, BALANCE, OVERDRAFT, PASSWORD, TYPE, OWNER_ID) VALUES (3, '22222222', 300000, 30000, 'jharden', 'current', 3);
